# Generated by Django 5.2.7 on 2025-10-14 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaoRecarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cartao', models.CharField(max_length=20, unique=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('USADO', 'Usado'), ('EXPIRADO', 'Expirado'), ('CANCELADO', 'Cancelado')], default='ATIVO', max_length=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_expiracao', models.DateTimeField()),
                ('data_uso', models.DateTimeField(blank=True, null=True)),
                ('cliente_uso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartoes_usados', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Cartão de Recarga',
                'verbose_name_plural': 'Cartões de Recarga',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Contador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=50, unique=True)),
                ('tipo_contador', models.CharField(choices=[('PRE_PAGO', 'Pré-pago'), ('POS_PAGO', 'Pós-pago')], max_length=10)),
                ('endereco_instalacao', models.TextField()),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('MANUTENCAO', 'Em Manutenção'), ('SUBSTITUIDO', 'Substituído')], default='ATIVO', max_length=15)),
                ('data_instalacao', models.DateField()),
                ('data_ultima_leitura', models.DateTimeField(blank=True, null=True)),
                ('leitura_atual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('potencia_maxima', models.DecimalField(decimal_places=2, help_text='Potência máxima em kW', max_digits=8)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contadores', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Contador',
                'verbose_name_plural': 'Contadores',
                'ordering': ['-data_instalacao'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_manutencao', models.CharField(choices=[('PREVENTIVA', 'Preventiva'), ('CORRETIVA', 'Corretiva'), ('SUBSTITUICAO', 'Substituição')], max_length=15)),
                ('descricao', models.TextField()),
                ('data_manutencao', models.DateTimeField()),
                ('tecnico_responsavel', models.CharField(max_length=200)),
                ('custo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('contador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_manutencao', to='equipamentos.contador')),
            ],
            options={
                'verbose_name': 'Histórico de Manutenção',
                'verbose_name_plural': 'Históricos de Manutenção',
                'ordering': ['-data_manutencao'],
            },
        ),
    ]
