# Generated by Django 5.2.7 on 2025-12-28 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_perfil'),
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contador',
            name='numero_cartao',
            field=models.CharField(blank=True, help_text='Número do cartão (apenas para pré-pago)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contador',
            name='tipo_conexao',
            field=models.CharField(choices=[('MONOFASICO', 'Monofásico'), ('TRIFASICO', 'Trifásico')], default='MONOFASICO', max_length=15),
        ),
        migrations.AlterField(
            model_name='contador',
            name='cliente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contador', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='contador',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('MANUTENCAO', 'Em Manutenção'), ('AVARIADO', 'Avariado'), ('SUBSTITUIDO', 'Substituído')], default='ATIVO', max_length=15),
        ),
    ]
