# Generated by Django 5.2.7 on 2025-12-28 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0002_contador_numero_cartao_contador_tipo_conexao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeituraConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leitura_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('leitura_atual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consumo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_leitura', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('contador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='equipamentos.contador')),
            ],
            options={
                'ordering': ['-data_leitura'],
            },
        ),
    ]
