# Generated by Django 5.2.9 on 2025-12-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0004_leituraconsumo_operador'),
    ]

    operations = [
        migrations.AddField(
            model_name='contador',
            name='data_suspensao',
            field=models.DateTimeField(blank=True, help_text='Data da suspensão por dívida', null=True),
        ),
        migrations.AlterField(
            model_name='contador',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('MANUTENCAO', 'Em Manutenção'), ('AVARIADO', 'Avariado'), ('SUBSTITUIDO', 'Substituído'), ('SUSPENSO', 'Suspenso por Dívida')], default='ATIVO', max_length=15),
        ),
    ]
