# Generated by Django 5.2.7 on 2026-05-27 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0005_contador_data_suspensao_alter_contador_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contador',
            name='tipo_contador',
        ),
    ]
