# Generated by Django 5.2.17 on 2026-08-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0007_alter_contador_numero_cartao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contador',
            name='numero_cartao',
            field=models.CharField(
                blank=True,
                help_text='Número do cartão, quando aplicável ao pagamento por recarga',
                max_length=20,
                null=True,
            ),
        ),
    ]