# Generated by Django 5.2.7 on 2025-12-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('DOMESTICA', 'Doméstica'), ('COMERCIAL', 'Comercial'), ('INDUSTRIAL', 'Industrial')], default='DOMESTICA', max_length=20)),
                ('preco_kwh', models.DecimalField(decimal_places=2, help_text='Preço por kWh em Kz', max_digits=10)),
                ('taxa_fixa', models.DecimalField(decimal_places=2, default=0.0, help_text='Taxa fixa mensal em Kz', max_digits=10)),
                ('ativa', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tarifa',
                'verbose_name_plural': 'Tarifas',
            },
        ),
    ]
