# Generated by Django 5.2.7 on 2025-12-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0002_tarifa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarifa',
            options={'verbose_name': 'Plano de Tarifa', 'verbose_name_plural': 'Planos de Tarifas'},
        ),
        migrations.AddField(
            model_name='tarifa',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição simples do plano/tarifa', null=True),
        ),
    ]
