# Generated by Django 5.2.7 on 2025-12-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0003_alter_tarifa_options_tarifa_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifa',
            name='preco_cliente_pos',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Taxa adicional fixa para clientes pós-pagos', max_digits=10, verbose_name='Preço p/ Cliente Pós-pago'),
        ),
        migrations.AddField(
            model_name='tarifa',
            name='preco_cliente_pre',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Taxa adicional fixa para clientes pré-pagos', max_digits=10, verbose_name='Preço p/ Cliente Pré-pago'),
        ),
    ]
