# Generated by Django 5.2.9 on 2025-12-28 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0004_tarifa_preco_cliente_pos_tarifa_preco_cliente_pre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pagamento', models.CharField(editable=False, max_length=30, unique=True)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pagamento', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('MULTICAIXA', 'Multicaixa')], max_length=20)),
                ('referencia_multicaixa', models.CharField(blank=True, help_text='Referência da transferência Multicaixa', max_length=100, null=True)),
                ('data_pagamento', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='pagamentos.fatura')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_pagamento'],
            },
        ),
    ]
