# Generated by Django 5.2.7 on 2025-12-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0005_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatura',
            name='juros_mora',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Juros de mora acumulados', max_digits=10),
        ),
        migrations.AddField(
            model_name='fatura',
            name='multa_atraso',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Multa por atraso (valor fixo)', max_digits=10),
        ),
    ]
