# Generated by Django 5.2.17 on 2026-08-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0006_fatura_juros_mora_fatura_multa_atraso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarifa',
            name='preco_cliente_pos',
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text='Taxa adicional fixa para clientes pagos por fatura',
                max_digits=10,
                verbose_name='Preço p/ Cliente Pago (fatura)',
            ),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='preco_cliente_pre',
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text='Taxa adicional fixa para clientes pagos por recarga',
                max_digits=10,
                verbose_name='Preço p/ Cliente Pago (recarga)',
            ),
        ),
    ]