# Generated by Django 5.2.7 on 2025-10-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioGerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo_relatorio', models.CharField(choices=[('CLIENTES_ATIVOS', 'Clientes Ativos/Inativos'), ('CONSUMO_AREA', 'Consumo Médio por Área'), ('PAGAMENTOS', 'Pagamentos Recebidos/Pendentes'), ('RECLAMACOES', 'Reclamações'), ('FINANCEIRO_DIARIO', 'Financeiro Diário'), ('FINANCEIRO_MENSAL', 'Financeiro Mensal')], max_length=30)),
                ('periodo_inicio', models.DateField()),
                ('periodo_fim', models.DateField()),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='relatorios/')),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('gerado_por', models.CharField(max_length=200)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Relatório Gerado',
                'verbose_name_plural': 'Relatórios Gerados',
                'ordering': ['-data_geracao'],
            },
        ),
    ]
