# Generated by Django 5.2.7 on 2025-12-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatoriogerado',
            name='tipo_relatorio',
            field=models.CharField(choices=[('CLIENTES_ATIVOS', 'Clientes Ativos/Inativos'), ('CONSUMO_AREA', 'Consumo Médio por Área'), ('PAGAMENTOS', 'Pagamentos Recebidos/Pendentes'), ('RECLAMACOES', 'Reclamações'), ('FINANCEIRO_DIARIO', 'Financeiro Diário'), ('FINANCEIRO_MENSAL', 'Financeiro Mensal'), ('CONSUMO_MENSAL', 'Consumo Mensal Detalhado')], max_length=30),
        ),
    ]
