# Generated by Django 5.2.7 on 2025-10-14 11:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cliente', models.CharField(editable=False, max_length=20, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('nif', models.CharField(max_length=20, unique=True, verbose_name='NIF')),
                ('bi', models.CharField(max_length=20, unique=True, verbose_name='BI')),
                ('morada', models.TextField()),
                ('telefone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Número de telefone inválido', regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tipo_cliente', models.CharField(choices=[('PRE_PAGO', 'Pré-pago'), ('POS_PAGO', 'Pós-pago')], default='PRE_PAGO', max_length=10)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('SUSPENSO', 'Suspenso')], default='ATIVO', max_length=10)),
                ('saldo_atual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_contrato', models.CharField(editable=False, max_length=30, unique=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('CANCELADO', 'Cancelado'), ('SUSPENSO', 'Suspenso')], default='ATIVO', max_length=10)),
                ('tarifa_kwh', models.DecimalField(decimal_places=2, default=10.0, max_digits=8)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
