# Generated by Django 5.2.7 on 2025-12-28 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_perfil'),
        ('pagamentos', '0002_tarifa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tarifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='pagamentos.tarifa'),
        ),
    ]
