# Generated by Django 5.2.17 on 2026-08-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_tarifa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(
                choices=[('PRE_PAGO', 'Pago - recarga'), ('POS_PAGO', 'Pago - fatura')],
                default='PRE_PAGO',
                max_length=10,
            ),
        ),
    ]